# Question 1

(A)

In [46]:
import numpy as np 
import random 
arr= np.random.randint(1,100,10)
print(arr)

[73 95 84 82  1 27 16 37 52 73]




(B)

In [47]:
last_element = arr[-1]
print(last_element)

73




(C)

In [48]:
float_array = np.random.rand(3, 3)
print(float_array)

[[0.81867845 0.10402436 0.22114912]
 [0.18776149 0.66604294 0.74811289]
 [0.27098535 0.31404956 0.34464876]]



# Question 2

(A)

In [49]:
first_row=float_array[0]
print(first_row)

[0.81867845 0.10402436 0.22114912]




(B)

In [50]:
last_col=float_array[:,-1]
print(last_col)

[0.22114912 0.74811289 0.34464876]




(C)

In [51]:
sub_arr=np.array(float_array[:2,:2])
print(sub_arr)

[[0.81867845 0.10402436]
 [0.18776149 0.66604294]]


# Question 3

(A)

In [52]:
array1=np.random.randint(1,100,size=5)
array2=np.random.randint(1,100,size=5)

array_add=array1+array2
print(array_add)

[184  54  88 143 163]



(B)

In [53]:
array_multi= array1*array2
print(array_multi)

[8428  200 1647 5022 6586]


(C)

In [54]:
array_square=array1[:]**2
print(array_square)

[9604   16 3721 3844 7921]


# Question 4

In [55]:
array_a=np.random.randint(1,100,size=(2,3))
array_b=np.random.randint(1,100,size=(3,2))

(A)

In [56]:
matrix_multi=np.dot(array_a,array_b)
print(matrix_multi)

[[ 5972 11640]
 [ 3630  5010]]


(B)
No you can not perform multiplication with * becaues the 2 matrixs are diffrent shapes, in order to multiply elements you have to use 'np.multiply(array_a,array_b)'